/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.example.notes.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Note service. Represents a row in the &quot;Notes_Note&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.notes.model.impl.NoteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.notes.model.impl.NoteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Note
 * @see com.example.notes.model.impl.NoteImpl
 * @see com.example.notes.model.impl.NoteModelImpl
 * @generated
 */
@ProviderType
public interface NoteModel extends BaseModel<Note>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a note model instance should use the {@link Note} interface instead.
	 */

	/**
	 * Returns the primary key of this note.
	 *
	 * @return the primary key of this note
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this note.
	 *
	 * @param primaryKey the primary key of this note
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the note ID of this note.
	 *
	 * @return the note ID of this note
	 */
	public long getNoteId();

	/**
	 * Sets the note ID of this note.
	 *
	 * @param noteId the note ID of this note
	 */
	public void setNoteId(long noteId);

	/**
	 * Returns the group ID of this note.
	 *
	 * @return the group ID of this note
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this note.
	 *
	 * @param groupId the group ID of this note
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this note.
	 *
	 * @return the company ID of this note
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this note.
	 *
	 * @param companyId the company ID of this note
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this note.
	 *
	 * @return the user ID of this note
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this note.
	 *
	 * @param userId the user ID of this note
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this note.
	 *
	 * @return the user uuid of this note
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this note.
	 *
	 * @param userUuid the user uuid of this note
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the content of this note.
	 *
	 * @return the content of this note
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this note.
	 *
	 * @param content the content of this note
	 */
	public void setContent(String content);

	/**
	 * Returns the priority of this note.
	 *
	 * @return the priority of this note
	 */
	public int getPriority();

	/**
	 * Sets the priority of this note.
	 *
	 * @param priority the priority of this note
	 */
	public void setPriority(int priority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Note note);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Note> toCacheModel();

	@Override
	public Note toEscapedModel();

	@Override
	public Note toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}